global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'core-service'
    metrics_path: /observability/metrics
    static_configs:
      - targets: ['core-service:3000']
  - job_name: 'rag-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['rag-service:8000']
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
